authuser/authuser/urls.py
from django.contrib import admin
from django.urls import path
from authuser import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.login_user,name='login_user'),
    path('signup/',views.signup,name='signup'),
    path('show/',views.show),
    path('homepage/',views.homepage,name='homepage'),
    path('edit/<int:id>', views.edit,name='edit'),
    path('update/<int:id>',views.update,name='update'),    
    path('delete/<int:id>',views.destroy, name='destroy'),
    path('crud_home/',views.addnew),
    path('crud_display/', views.inde),
    path('account/login',views.login_user),
    path('logout',views.logout_view),
    path('edit_user/<int:id>/', views.signup_edit, name='signup_edit'),
    path('signup_update/<int:user_id>',views.signup_update, name='signup_update'),
    path('delete_user/<int:id>/',views.signup_destroy,name='signup_destroy'),
]

authuser/combon/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Emp(models.Model):  
    empid = models.CharField(max_length=100)
    name = models.CharField(max_length=100)  
    email = models.EmailField()  
    contact = models.CharField(max_length=15) 
   
    class Meta:  
        db_table = "emp"


class Dhan(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phoneno = models.CharField(max_length=15)
    dob = models.CharField(max_length=20)
    address = models.CharField(max_length = 100, blank=True)
    # username = models.CharField(max_length=50)
    # password = models.TextField(max_length=50)
    class Meta:
        db_table = "dhan"

@receiver(post_save,sender=User)
def create_dhan(sender,instance,created,**kwargs):
    if created:
        Dhan.objects.create(user=instance)

@receiver(post_save,sender=User)
def save_dhan(sender,instance,**kwargs):
    instance.dhan.save()

authuser/combon/forms.py
from django import forms
from combon.models import Emp,Dhan


class LoginForm(forms.ModelForm):
    username = forms.CharField(max_length=150, required=True)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput, required=False)
    class Meta:
        model = Dhan
        fields= ["phoneno","dob","address"]
        widgets = {
            # 'username' : forms.TextInput(attrs={'class': 'form-control'}),
            'phoneno' : forms.TextInput(attrs={'class': 'form-control'}),
            'dob' : forms.DateInput(attrs={'class': 'form-control'}),
            'address' : forms.TextInput(attrs={'class': 'form-control'}),
            # 'password' : forms.TextInput(attrs={'class': 'form-control'}),
        }

    def _init_(self, *args, **kwargs):
        user_instance = kwargs.pop('user_instance', None)
        super(LoginForm, self)._init_(*args, **kwargs)
        if user_instance:
            self.user_instance = user_instance
            self.fields['username'] .initial = user_instance.username
            self.fields['password'].widget.attrs['placeholder'] = 'Enter new password'

class EmpForm(forms.ModelForm):  
    class Meta:  
        model = Emp 
        fields = '__all__'
        widgets = {
            'empid' : forms.TextInput(attrs={'class': 'form-control'}), 
            'name' : forms.TextInput(attrs={'class': 'form-control'}), 
            'email' : forms.EmailInput(attrs={'class': 'form-control'}),
            'contact' : forms.TextInput(attrs={'class': 'form-control'}),
        }


authuser/authuser/views.py
from django.shortcuts import redirect, render
from combon.models import Emp, Dhan
from django.http import HttpResponse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from combon.forms import  EmpForm, LoginForm 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.cache import cache_control

def signup(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        us=request.POST['username']
        pa=request.POST['password']
        use =User.objects.create_user(username=us, password=pa)
        Dhan.objects.filter(user=use).update(phoneno=request.POST['phoneno'],dob=request.POST['dob'],address=request.POST['address'])
        # if form.is_valid():
        #     form.save()
        return redirect("/")
    else:
        form = LoginForm()
    return render(request,'signup.html', {'form': form})
        

def homepage(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
                form.save() 
                return redirect("/show")
    else:
        form = UserCreationForm()
    return render(request,"homepage.html",{'form':form})

def login_user(request):
    if request.method == 'POST':
       use=request.POST['user_name']
       use2=request.POST['user_password']
       use3=authenticate(request,username=use, password=use2)
       if use3:
           login(request, use3)
           return redirect('/crud_home')
       else:
           return HttpResponse('Invalid User name or password')
       
    else:
           return render(request,"login.html")
    
          
def show(request):
    dha= Dhan.objects.all()
    return render(request,'show.html',{'dha':dha})


@login_required(login_url="/")
@cache_control(no_cache=True, must_revalidate=True, no_store=True)

def addnew(request):  
    if request.method == "POST":  
        form= EmpForm(request.POST)  
        if form.is_valid():  
            form.save()  
            return redirect('/crud_display') 
    else:  
        form = EmpForm()  
    return render(request,'crud_home.html',{'form':form})  

def inde(request):  
    crs = Emp.objects.all()  
    return render(request,"crud_display.html",{'crs':crs})  

def edit(request,id):  
    crs = Emp.objects.get(id=id)  
    return render(request,'edit.html', {'crs':crs})  

def update(request,id):  
    crs = Emp.objects.get(id=id)  
    form= EmpForm(request.POST, instance=crs)  
    if form.is_valid():  
        form.save()  
        return redirect('/crud_display')  
    return render(request, 'edit.html', {'crs':crs})  
     
def destroy(request,id):  
    crs = Emp.objects.get(id=id)  
    crs.delete()  
    return redirect('/crud_display')

def logout_view(request):
    logout(request)
    return redirect("/")

# signup_crud

def signup_inde(request):  
    sgn = Dhan.objects.all()  
    return render(request,"show.html",{'sgn':sgn})  

def signup_edit(request,id):  
    sgn = User.objects.get(id=id)  
    return render(request,'signup_edit.html', {'sgn':sgn})  

# def signup_update(request,id):  
#     sgn, created = Dhan.objects.get_or_create(user=request.user)  
#     form= LoginForm(request.POST, instance=sgn)
#     if request.method=='POST': 
#             if form.is_valid():  
#                 form.save()  
#                 return redirect('/show')  
#     return render(request, 'signup_edit.html', {'form':form})  
     
def signup_destroy(request,id):  
    sgn = User.objects.get(id=id)  
    sgn.delete()  
    return redirect('/show')

def signup_update(request,user_id):
    user = User.objects.get(pk=user_id)
    custom_user = Dhan.objects.get(user=user)
    
    if request.method == 'POST':
        form = LoginForm(request.POST, instance=custom_user)
        
        if form.is_valid():
            user.username = form.cleaned_data['username']
            user.set_password(form.cleaned_data['password'])
            user.save()
            custom_user.address = form.cleaned_data['address']
            custom_user.dob = form.cleaned_data['dob']
            custom_user.phoneno = form.cleaned_data['phoneno']
            custom_user.save()
        
            return redirect('/show')
    else:
        form = LoginForm(instance=custom_user)
    return render(request, 'show.html', {'form': form})

authuser/combon/views.py
from django.shortcuts import render

# Create your views here.

authuser/templates/crud_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    
    <div class="container">
        <table class="table table-border table-bordered text-center shadow">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Edit/Delete</th>
            </tr>
        
        {% for cr in crs %}  

            <tr>  
                <td>{{cr.empid}}</td>   
                <td>{{cr.name}}</td>  
                <td>{{cr.email}}</td>  
                <td>{{cr.contact}}</td>  
                <td><a href="/edit/{{cr.id}}" class="btn btn-success" >Edit</a>
                <a href="/delete/{{cr.id}}" class="btn btn-danger">Delete</a></td>  
            </tr>  
        {% endfor %} 
        </table>
</body>
</html>

authuser/templates/crud_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <form method="POST"  class="post-form"action="">  
        {% csrf_token %}  
          
            <h3>Enter Employee Details</h3>  
                <div class="mb-3"> 
                    <label>Empid:</label>  
                    {{form.empid}} 
                </div>
            
                <div class="mb-3">
                    <label>Name:</label>  
                    {{form.name}} 
                </div>

                <div class="mb-3">
                    <label>Email:</label>  
                    {{form.email}}  
                </div>

                <div class="mb-3">
                    <label>Contact:</label>  
                    {{form.contact}}   
                </div>            
                <button type="submit" name="addnew" class="btn btn-success">Submit</button>   
                <a href="/crud_display" class="btn btn-success">Database</a>
                <a href= "/logout" class="btn btn-danger">Logout</a>
            </div> 
        </div>  
        </form>   
    </div>
</body>
</html>

authuser/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>
<body>
    <div class="container">
    <form method="POST"  action="/update/{{crs.id}}">  
        {% csrf_token %}  
            <div class="form-group"><br><br>
                <label>Employee ID:</label>  
                <input type="text"  name="empid"  value="{{crs.empid}}"/>    
            </div><br>    

            <div class="form-group">
                <label>Name:</label>  
                <input type="text"  name="name"  value="{{crs.name}}" />  
            </div><br>   

            <div class="form-group">
                <label>Email:</label>  
                <input type="email"  name="email"  value="{{crs.email}}" />  
            </div><br>  
            
            
             <div class="form-group">
                <label>Contact:</label>  
                <input type="text"  name="contact" id="id_contact"  value="{{crs.contact}}" />  
            </div><br>  

            <button type="submit" name="update" class="btn btn-success">Update</button>  
            </div> 
        </div>  
        </form>         
    </div>   
</body>
</html>

authuser/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LOGIN</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
        <div class="container">
        <form method="POST" action="">
            {% csrf_token %}
            
            <h1>login</h1>
            <br><br>

            <label>UserName:</label>
            <input type="text" name='user_name' >
            <br><br>

            <label>Password:</label>
            <input type="password" name='user_password' >
            <br><br><br>
            
            <button type="submit" name="login_user" class="btn btn-success">Login</button>   
            <a href="signup/" class="btn btn-sm"> Create Accout</a>  
             

</form>
</fieldset>
</div>
</body>
</html> 

authuser/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <table class="table table-border table-bordered text-center shadow">
        <tr></br>
           
            <th>UserName</th>
            <th>Phone No</th>
            <th>DOB</th>
            <th>Address</th>
            <th>Password</th>  
            <th>Edit/Delete</th>
        </tr>

        {% for i in dha %}

        <tr>
           
            <td>{{i.user.username}}</td>
            <td>{{i.phoneno}}</td>
            <td>{{i.dob}}</td>
            <td>{{i.address}}</td>
            <td>{{i.user.password}}</td>
            <td><a href="/edit_user/{{i.user.id}}" class="btn btn-success" >Edit</a>
                <a href="/delete_user/{{i.user.id}}" class="btn btn-danger">Delete</a></td>  
        </tr>

        {% endfor %}
        
    </table>
</body>
</html> 

authuser/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignUp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <form method="POST" action="">
        {% csrf_token %}

            <h3>SIGNUP</h3>
            <br><br>
             
            <div class="form-group">
            <label>UserName:</label>
            <input type ='text' name ='username' class="" placeholder="enter the name ">
            <br><br>

            <div class="form-group">
            <label>Phone No:</label>
            <input type ='text' name ='phoneno' class="" placeholder="enter the phoneno ">
            <br><br>

            <div class="form-group">
            <label>DOB:</label>
            <input type ='text' name ='dob' class="" placeholder="enter the dob ">
            <br><br>

            <div class="form-group">
            <label>Address:</label>
            <input type ='text' name ='address' class="" placeholder="enter the address ">
            <br><br>

            <div class="form-group">
            <label>Password:</label>
            <input type ='text' name ='password' class="" placeholder="enter the password ">
            <br><br>
            
            <button type="submit" name="signup" class="btn btn-success">Submit</button>    
            <a href="/show" class="btn btn-danger">Database</a>
            
        </div>
        </div>
</form>
</div>
</body>
</html> 

authuser/templates/signup_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>
<body>
    <div class="container">
    <form method="POST"  action="/signup_update/{{sgn.id}}">  
        {% csrf_token %}  
            <div class="form-group"><br><br>
                <label>UserName:</label>  
                <input type="text"  name="username"  value="{{sgn.username}}"/>    
            </div><br>    

            <div class="form-group">
                <label>Phone No:</label>  
                <input type="text"  name="phoneno"  value="{{sgn.dhan.phoneno}}" />  
            </div><br>   

            <div class="form-group">
                <label>DOB:</label>  
                <input type="dob"  name="dob"  value="{{sgn.dhan.dob}}" />  
            </div><br>  
            
             <div class="form-group">
                <label>Address:</label>  
                <input type="text"  name="address"  value="{{sgn.dhan.address}}" />  
            </div><br>  

            <div class="form-group">
                <label>Password:</label>  
                <input type="password"  name="password" value="{{sgn.password}}" />  
            </div><br>  

            <button type="submit" name="update" class="btn btn-success">Update</button>  
            </div> 
        </div>  
        </form>         
    </div>   
</body>
</html>